name: Deploy to Render using Docker

on:
  workflow_dispatch:  # Allows manual triggering

env:
  RENDER_SERVICE_ID: ${{ vars.RENDER_SERVICE_ID }}  # Using GitHub Environment Variable
  

jobs:
  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub securely
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/librarify:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/librarify:latest

      - name: Trigger Render Deployment
        run: |
          curl -X POST "https://api.render.com/v1/services/${{ env.RENDER_SERVICE_ID }}/deploys" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -H "Accept: application/json" \
          -d ''
